language: ruby
rvm:
  - 1.9.3
    gemfile: spec/gemfiles/Gemfile.ruby19
    env: ISOLATED=true
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-19mode
    gemfile: spec/gemfiles/Gemfile.ruby19
    env: ISOLATED=true
  - rbx
env:
  global:
    - NYULIBRARIES_APPLICATION_ID=app_id
