language: ruby
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - rbx-2
before_install:
  - gem install bundler
  - gem update bundler
  - bundler --version
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: 2.1.10
env:
  global:
    - NYULIBRARIES_APPLICATION_ID=app_id
sudo: false
